name: yolov4-cpu1

dependencies:
  - python==3.7.4
  - pip
  - matplotlib
  - opencv
  - pip:
    - opencv-python==4.1.1.26
    - lxml
    - tqdm
    - tensorflow==2.3.0
    - absl-py
    - easydict
    - pillow
    - pytesseract